services:
  - type: web
    name: blog-search-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: QDRANT_HOST
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
